config/routes.rb
Rails.application.routes.draw do
  get '/top'      => 'home#top'
  get '/photo'    => 'home#photo'
  get '/profile'  => 'home#profile'
  get '/schedule' => 'home#schedule'
  get '/movie'    => 'home#movie'

  root 'home#top'

  resources :photo_products
    get '/index' => 'photo_products#index'

end

app/models/photo_product.rb
class PhotoProduct < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/photo_products_controller.rb
class PhotoProductsController < ApplicationController
  before_action :set_photo_product, only: [:show, :edit, :update, :destroy]

  # GET /photo_products
  # GET /photo_products.json
  def index
    @photo_products = PhotoProduct.all
    # @user_images = current_user.upload
  end

  # GET /photo_products/1
  # GET /photo_products/1.json
  def show
  end

  # GET /photo_products/new
  def new
    @photo_product = PhotoProduct.new
  end

  # GET /photo_products/1/edit
  def edit
  end

  # POST /photo_products
  # POST /photo_products.json
  def create
    @photo_product = PhotoProduct.new(photo_product_params)

    respond_to do |format|
      if @photo_product.save
        format.html { redirect_to @photo_product, notice: 'Photo product was successfully created.' }
        format.json { render :show, status: :created, location: @photo_product }
      else
        format.html { render :new }
        format.json { render json: @photo_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_products/1
  # PATCH/PUT /photo_products/1.json
  def update
    respond_to do |format|
      if @photo_product.update(photo_product_params)
        format.html { redirect_to @photo_product, notice: 'Photo product was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_product }
      else
        format.html { render :edit }
        format.json { render json: @photo_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_products/1
  # DELETE /photo_products/1.json
  def destroy
    @photo_product.destroy
    respond_to do |format|
      format.html { redirect_to photo_products_url, notice: 'Photo product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_product
      @photo_product = PhotoProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_product_params
      # permit()に:image, :image_cache, :remove_imageを追加
      params.require(:photo_product).permit(:name, :price, :image, :image_cache, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photo_products_helper.rb
module PhotoProductsHelper
end

app/views/home/profile.html.slim
#profilePage
  .event
    h1 Live・イベント出演
    p
      | ・TGC  2015 2月 ダイワハウスダンサー出演
      br
      | ・TGC 2015 2月 PUNYUSダンサー出演
      br
      | ・TGC 2014 3月 ダイワハウス渡辺直美さんアシスト
      br
      | ・TGC 2014 9月 ダイワハウスダンサー出演
      br
      | ・YU-Aさん 2015 ワールドワイドダんさー出演
      br
      | ・Leadさん 2015ワールドワイドダンサー出演
      br
      | ・YU-Aさん 2013 ワールドワイドダンサー出演
      br
      | ・YU-Aさん 2012 ワールドワイドダンサー出演
      br
      | ・紅白歌合戦2014 嵐さんバックダンサー出演
      br
      | ・TOKINEさん NYLONJAPAN バックダンサー出演
      br
      | ・JUJUさん MV出演 「play back」
  .assistant
    h1 振り付けコレオグラファーアシスタント
    p
      | ・安室奈美恵さん 
      br
      | ・アフタースクールさん
      br
      | ・板野友美さん
      br
      | ・浜崎あゆみさん

app/views/home/top.html.slim
#profile
  article
    .profile-all
      .profile-jp
        p
          | 名前：菊池恵里沙(キクチ エリサ)
          br
          | ダンサーネーム：ERISA
          br
          | 生年月日：1992.8.15
          br
          | 年齢：22歳
          br
          | 身長：154センチ
          br
          | 出身：東京
      .profile-eg
        p
          | name：Erisa Kikuchi
          br
          | dancer name：ERISA
          br
          | birthday：August 15.1992
          br
          | age：23
          br
          | height：5'1"
          br
          | from：Tokyo
      .record
        h3 Dance record
        p
          | profile-record
          br
          | 11 years
          br
          | Jazz：11 years
          br
          | JazzFunk：10 years
          br
          | HipHop：11 years
          br
          | House：3 years
          br
          | Lockin：3 years
          br
          | Punking：6 years
          br
          | Popin：3 years


/** slider**/



/** slider**/
.slider
  .container
    .loopslider
      ul
        li
          a(href="#")
            img(src="../assets/images/eri01.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri02.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri03.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri04.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri05.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri07.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri08.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri09.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri11.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri12.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri13.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri14.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri15.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri16.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri17.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri18.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri19.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri20.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri21.jpg" width="150" height="150" alt="")
        li
          a(href="#")
            img(src="../assets/images/eri22.jpg" width="150" height="150" alt="")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Erisa</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= content_for :js %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
	<h1><%= link_to "ERISA", root_path %></h1>
	<nav>
		<ul>
			<li>
				<%= link_to "HOME", root_path %>
				<%= link_to "PROFILE", profile_path %>
				<%= link_to "SCHEDULE", schedule_path %>
				<%= link_to "PHOTO", photo_path %>
				<%= link_to "MOVIE", movie_path %>
			</li>
		</ul>
	</nav>
</header>

<%= yield %>

<footer>
	<div class="footer">
		<h1 class="footer-title">Contact</h1>
		<form method="POST" action="">
			<p class="footer-font">Name：<br><input type='text' name="name" size="22"></p>
			<p class="footer-font">E-mail：<br><input type="text" name="email" size="22"></p>
			<p class="footer-font">Comment：<br><textarea name=""comment cols="20" rows="5"></textarea></p></form>
			<button class="button-footer" type="submit">send</button>
		</form>
	</div>
	<div class="icon">
		<div class="tw">
			<a href="https://twitter.com/search?q=%400815Essa&src=typd"><img src="../assets/images/icons/icon_Twitter.png" width="80px" height="80px" alt="twitter"></a>
		</div>
		<div class="fb">
			<a href="https://www.facebook.com/erisa.kikuchi"><img src="../assets/images/icons/icon_Facebook.png" width="80px" height="80px" alt="facebook"></a>
		</div>
		<div class="in">
			<a href="https://www.instagram.com/erisa.k815/"><img src="../assets/images/icons/icon_Instagram.png" width="80px" height="80px" alt="Instagram"></a>
		</div>
	</div>
</footer>

</body>
</html>

app/views/photo_products/_form.html.slim
= form_for @photo_product do |f|
  - if @photo_product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@photo_product.errors.count, "error")} prohibited this photo_product from being saved:"
      ul
        - @photo_product.errors.full_messages.each do |message|
          li = message

  /* nameからtitleに変更*/
  .field
    = f.label :title
    = f.text_field :title, size: "40x10", maxlength: "30"

  /* commnet追加*/
  .field
    = f.label :comment
    = f.text_area :comment, size: "30x10", maxlength: 30

  /* 追加箇所 開始*/
  .field
    = if @photo_product.image?
      .thumbnail
        = image_tag @photo_product.url
    = f.label :image
    / = f.file_field :image
    = f.file_field :image, class: 'form-control'
    = f.hidden_field :image_cache
  .field
    /* DBに保存されているかつ、画像が保存する場合*/
    - if @photo_product.persisted? && @photo_product.image?
      label
        = f.check_box :remove_image
        p 画像を消去
  /* 追加箇所 終了*/

  .actions = f.submit

app/views/photo_products/edit.html.slim
h1 Editing photo_product

== render 'form'

= link_to 'Show', @photo_product
'|
= link_to 'Back', photo_products_path

app/views/photo_products/index.html.slim
center
  .form
    h1.form Upload Photo

    table
      thead
        tr
          th.title Title
          th.title Comment

      tbody
        - @photo_products.each do |photo_product|
          tr
            td = photo_product.title
            td = photo_product.comment
            td = link_to 'Show', photo_product
            td = link_to 'Edit', edit_photo_product_path(photo_product)
            td = link_to 'Destroy', photo_product, data: {:confirm => 'Are you sure?'}, :method => :delete
    .newPhotoButton
      h1.form
        = link_to 'New Photo product', new_photo_product_path

app/views/photo_products/new.html.slim
center
  h1.new Please choose photo

  h2.new
    == render 'form'
  h1.new
    = link_to 'Back', photo_products_path

app/views/photo_products/show.html.slim
center
  p#notice = notice

  p.title
    strong Title:
    = @photo_product.title

  /* 追加箇所　開始*/
  p.img
    strong Image:
    - if @photo_product.image?
      .thumbnail
        = image_tag @photo_product.image.url
  /* 追加箇所　終了*/

  p.comment
    strong Comment:
    = @photo_product.comment

  .btn
    h1.show
      = link_to 'Edit', edit_photo_product_path(@photo_product)
      = link_to 'Back', photo_products_path